config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :boats do
    resources :reservations, only: [:create, :new, :edit]
  end
  # delete '/boats/:id', to: 'boats#destroy', as: 'boat_delete'
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :boats, only: %i[show destroy]
  resources :reservations

  get 'my_reservations', to: 'reservations#my_reservations'
  # Defines the root path route ("/")
  # root "articles#index"
  # resources :boats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address

  after_validation :geocode, if: :will_save_change_to_address?
  validates :address, :boat_type, :total_occupancy, :price, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable

  belongs_to :boat
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  has_many :boats
  has_many :reservations
  has_many :rented_boats, through: :reservations, source: :boat
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :find_by_id, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def new
    @boat = Boat.new
  end

  def index
    @boats = Boat.all

    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { boat: boat })
      }
    end
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user_id = current_user.id
    if @boat.save!
      redirect_to boat_path(@boat)
    else
      render :new
    end
  end

  def update
    @boat.update(boat_params)
    redirect_to boat_path(@boat)
  end

  def show
    @boat = Boat.find(params[:id])
    @reservation = Reservation.new
  end

  def destroy
    # @boat = Boat.find(params[:id])
    @boat.destroy
    redirect_to boats_path, status: :see_other
  end

  private

  def find_by_id
    @boat = Boat.find(params[:id])
  end

  def boat_params
    params.require(:boat).permit(:boat_type, :location, :total_occupancy, :price, :address, :photo)
  end
end

  #Below should all go into HTML file in view
  #Methoden aus dem Schema

  #def boat_type
  #end

  #def owner_id
    #Anders als nur user Eingabe
  #end

  #def location
  #end

  #def total_occupancy
  #end

  #def price
  #end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @boats = Boat.limit(6).order(created_at: :desc)
  end
end

app/controllers/reservations_controller.rb
require 'date'

class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.find(params[:boat_id])
    @reservation = Reservation.new
  end

  def create
    @boat = Boat.find(params[:boat_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.boat = @boat
    @reservation.user = current_user
    if @reservation.save
      redirect_to reservation_path(@reservation), notice: 'Reservation was successfully created.'
    else
      render 'boats/show', status: :unprocessable_entity
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @Reservation = Reservation.find(params[:id])
  end

  def my_reservations
    @my_reservations = Reservation.where(user: current_user)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boat/boat-view.html.erb
<html>
 <head>
 <title>Homepage</title>
  # <meta>  i dunno what to put in here </meta>
   <link rel="stylesheet" href="style.css">
 </head>

 <body>
  <div class="outer-frame">
   <h1> "WATER BNB" </h1>
   <h2> "For all your boating needs to enable all to ride the high seas "</h2>
   #<h3> "I have a boat"</h3>
   <h3> "Le Wagon" </h3>
    <a href "#" class="btn-1">"Browse"</a>
    <a href "#" class="btn-3">"Add your own boat"</a>
    <a href="#" class="btn-3">"Confab"</a>
    <a href="#" class="btn-login">"+ Login"</a>
    #app mascot
  </div>
  <div class="banner" style=#"background-image: url(images/background.png);">
    <div class="card">
      <h1>"Get Yer Boats Here"</h1>
      <h2>"Big and small and sunk and float"</h2>
      <h2>"The Boat Squad"</h2>
      <h3>"I have a boat"</h3>
      <p>"patent pending"</p>
      #arrow logo
      <a class="btn-contacts" href="#" #logo</a>
      <a class="btn-notification" href="#" #logo</a>
      #überlappender kreis
    </div>
  </div>

  #images
</body>
</html>

app/views/boats/_boat_card.html.erb
<div class="boat_card col-8 col-md-4 col-lg-3 m-3 px-4 rounded" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%=     cl_image_path boat.photos.first.key %>');">
  <h3><%= boat.boat_id %></h3>
  <%= link_to "View Listing", boat, class: "btn btn-outline-light rounded-pill m-4" %>
</div>

app/views/boats/_form.html.erb
<%= simple_form_for @boat do |f| %>
  <div class="form-inputs">
    <%= f.input :boat_type, label: false, placeholder: 'Boat Name', input_html: { class:'boat-input' } %>
    <%= f.input :total_occupancy, label: false, placeholder: 'Total Occupancy', input_html: { class:'boat-input' } %>
    <%= f.input :price, as: :numeric, label: false, placeholder: 'Price?', input_html: { class:'boat-input' } %>
    <%= f.input :address %>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="form-actions d-flex justify-content-center mt-5">
    <%= f.button :submit, class:'btn btn-ghost' %>
  </div>

<% end %>

app/views/boats/_info_window.html.erb
<h2><%= boat.boat_type %></h2>
<p><%= boat.address %></p>

app/views/boats/index.html.erb
<div>
  <h1 class="boat-index-title">List o' Water Wagons</h1>
  <div class= "button">
    <%= link_to "New Boat", new_boat_path, class: "btn-add-new" %>
  </div>
</div>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>




  <% @boats.each do |boat| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path boat.photo.key %>)">
      <%= link_to boat.boat_type, boat_path(boat), class: "btn btn-ghost" %>
    </div>
  <% end %>
</div>

app/views/boats/new.html.erb
<%= render "form" %>

app/views/boats/show.html.erb
<div class="container">
  <div class="boat-row d-flex justify-content-between">
    <div class="boat-card" style="width: 30rem;">
     <%= cl_image_tag @boat.photo.key, height: 300, width: 480, crop: :fill, class: "boat-card-img" %>
      <div class="boat-card-body">
        <h1><%= @boat.boat_type %></h1>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Type of Boat:</strong> <%= @boat.boat_type %></li>
        <li class="list-group-item"><strong>Capacity:</strong> <%= @boat.total_occupancy %></li>
        <li class="list-group-item"><strong>Price:</strong> <%= @boat.price %></li>
      </ul>
      <br>
      <p><%= link_to "Delete", boat_path(@boat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-boat-btn"  %></p>
    </div>

    <div class="col-4 mt-5">
      <%= simple_form_for [@boat, @reservation] do |f| %>
        <%= f.input :start_date, as: :date, html5: true%>
        <%= f.input :end_date, as: :date, html5: true %>
        <div class="d-flex justify-content-center mt-4.5 py-2">
          <%= f.submit "Book Boat Boi", class:"button_64" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Water</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
   <%# <p class="notice">= notice</p> %>
   <%# <p class="alert">= alert</p> %>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div style= "min-height: (100vh - 166.16px)" class="background-style">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-container">
  <h1 class="title">Water Boats N Barges</h1>
  <h1 class="title title-large">Water Boats N Barges</h1>
  <div id="img-1" class="img-container">
    <img class="img" src="https://culturecdn.fra1.cdn.digitaloceanspaces.com/2018/04/Tall-Ships-016.jpg">
  </div>

  <div class="img-container second-animation">
    <img class="img" src="https://www.tresco.co.uk/uploads/pdfs/_500x357_crop_center-center_none/SEAF18-0942.jpg?v=1643299944">
  </div>

  <div class="img-container third-animation">
    <img class="img" src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/18/2022/01/monte-carlo-yachts-105-skylounge-aft-view-630x354.jpg">
  </div>

  <div class="img-container fourth-animation">
    <img class="img nba" src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/8/2017/09/boat6.jpg">
  </div>

  <div class="img-container fifth-animation">
    <img class="img" src="https://classic-sailing.com/wp-content/uploads/2020/06/from_facebook_permission_requested_-_europa_1.jpg">
  </div>

  <div id="img-6" class="img-container sixth-animation">
    <img class="img" src="https://www.cruisemapper.com/images/ships/2077-f3109b8affb.jpg">
  </div>

  <div id="img-7" class="img-container seventh-animation">
    <img class="img" src="https://gofreediving.co.uk/wp-content/uploads/2017/05/Go-Freediving-10-things-you-can-find-underwater-underwater-post-office.jpg">
  </div>
</div>


  <div class="container">
    <div class="content">
</div>
  <%= link_to "Get yer boats 'ere", "boats", class: "btn btn-ghost" %>
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.bavariayachts.com/fileadmin/_processed_/5/c/csm_bavaria-home-map-mb_7358dfff3a.jpg)">
    <%= link_to "Great Boats", "boats", class: "btn btn-ghost" %>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.marineinsight.com/wp-content/uploads/2021/06/Dinghy-Boats.jpg.webp)">
    <%= link_to "Ok Boats", "boats", class: "btn btn-ghost" %>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://m.belfasttelegraph.co.uk/news/northern-ireland/b98c9/41555382.ece/AUTOCROP/w620/wreck)">
    <%= link_to "Historic Boats", "boats", class: "btn btn-ghost" %>
  </div>
</div>

app/views/reservations/_form.html.erb
<%= simple_form_for(@boat, @reservation) do |f| %>
  <div class="form-inputs">
    <%= f.input :boat_id, label: false, placeholder: 'Boat Name', input_html: {class:'boat-input'} %>
    <%= f.input :total_occupancy, label: false, placeholder: 'Total Occupancy', input_html: {class:'boat-input'} %>
    <%= f.input :price, as: :numeric, label: false, placeholder: 'Price?', input_html: {class:'boat-input'} %>
  </div>
  <div class="form-actions d-flex justify-content-center mt-5">
    <%= f.button :submit, class:'boat-button' %>
  </div>

<% end %>

app/views/reservations/my_reservations.html.erb
<div class="container text-center mt-5">
  <h3>Find yer bookings 'ere </h3>
  <div class="row justify-content-center">
    <% @my_reservations.each do |reservation| %>
          <%= cl_image_tag reservation.boat.photo.key, height: 300, width: 296, crop: :fill, class: "boat-card-img" %>
        <div class="card-product-infos">
          <h2><%= reservation.boat.boat_type %></h2>
          <p>£<%= reservation.boat.price %></p>
        </div>
        <div class="ps-2">
          <p style="font-size:10px"><strong>From</strong><br> <%= reservation.start_date.strftime("%B %d") %></p>
          <p style="font-size:10px; margin:0" class="pt-1"><strong>To</strong><br> <%= reservation.end_date.strftime("%B %d") %></p>
        </div>
          <%= link_to ">", reservation.boat, class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/reservation-view.html.erb
<html>
 <head>
  <meta></meta>
 </head>


 <body>
 
 </body>
</html>

app/views/reservations/show.html.erb
<h1 class="greeting">✔ Congratulations in hooking the amazing vessel <%= @reservation.boat.boat_type %></h1>

<h2>Booking start date: <%= @reservation.start_date %></h1>
<h2>Booking end date: <%= @reservation.end_date %></h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-container container d-flex justify-content-between">
    <ul class="list-inline footer-links">
      <li><a class="footer-link" href="#"><i class="fab fa-instagram"></i></a></li>
      <li><a class="footer-link" href="#"><i class="fab fa-facebook"></i></a></li>
      <li><a class="footer-link" href="#"><i class="fab fa-twitter"></i></a></li>
      <li><a class="footer-link" href="#"><i class="fab fa-linkedin"></i></a></li>
    </ul>
    <ul class="list-inline footer-copyright">
      <li><a class="footer-link" href="#">About us</a></li>
      <li><a class="footer-link" href="#">Terms</a></li>
      <li><a class="footer-link" href="#">Privacy</a></li>
    </ul>
  </div>
  <div class="box-drift">
    <div class="box-bob">
      <div class="box-pitch">
        <div class="left-sail"></div>
        <div class="right-sail"></div>
        <div class="hull"></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn.pixabay.com/photo/2020/09/24/18/04/ship-5599389_1280.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://miro.medium.com/max/886/1*MOSC_3urG8VqbHbzpMpepw.jpeg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Reservations", my_reservations_path, class: "dropdown-item" %>
              <%= link_to "Messages", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>